<?php

	return array(
		array(
			'g_country_id'	=> '30',
			'g_total_regions'	=> '32',
			'g_total_cities'	=> '29204',
			'g_title_ru'	=> 'Афганистан',
			'g_title_en'	=> 'Afghanistan',
		),
		array(
			'g_country_id'	=> '21',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '4587',
			'g_title_ru'	=> 'Албания',
			'g_title_en'	=> 'Albania',
		),
		array(
			'g_country_id'	=> '22',
			'g_total_regions'	=> '48',
			'g_total_cities'	=> '6694',
			'g_title_ru'	=> 'Алжир',
			'g_title_en'	=> 'Algeria',
		),
		array(
			'g_country_id'	=> '23',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '161',
			'g_title_ru'	=> 'Американское Самоа',
			'g_title_en'	=> 'American Samoa',
		),
		array(
			'g_country_id'	=> '26',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '65',
			'g_title_ru'	=> 'Андорра',
			'g_title_en'	=> 'Andorra',
		),
		array(
			'g_country_id'	=> '25',
			'g_total_regions'	=> '18',
			'g_total_cities'	=> '8910',
			'g_title_ru'	=> 'Ангола',
			'g_title_en'	=> 'Angola',
		),
		array(
			'g_country_id'	=> '24',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '37',
			'g_title_ru'	=> 'Ангилья',
			'g_title_en'	=> 'Anguilla',
		),
		array(
			'g_country_id'	=> '27',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '129',
			'g_title_ru'	=> 'Антигуа и Барбуда',
			'g_title_en'	=> 'Antigua and Barbuda',
		),
		array(
			'g_country_id'	=> '28',
			'g_total_regions'	=> '24',
			'g_total_cities'	=> '6727',
			'g_title_ru'	=> 'Аргентина',
			'g_title_en'	=> 'Argentina',
		),
		array(
			'g_country_id'	=> '6',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '989',
			'g_title_ru'	=> 'Армения',
			'g_title_en'	=> 'Armenia',
		),
		array(
			'g_country_id'	=> '29',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '106',
			'g_title_ru'	=> 'Аруба',
			'g_title_en'	=> 'Aruba',
		),
		array(
			'g_country_id'	=> '19',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '9860',
			'g_title_ru'	=> 'Австралия',
			'g_title_en'	=> 'Australia',
		),
		array(
			'g_country_id'	=> '20',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '17161',
			'g_title_ru'	=> 'Австрия',
			'g_title_en'	=> 'Austria',
		),
		array(
			'g_country_id'	=> '5',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '3239',
			'g_title_ru'	=> 'Азербайджан',
			'g_title_en'	=> 'Azerbaijan',
		),
		array(
			'g_country_id'	=> '31',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '355',
			'g_title_ru'	=> 'Багамы',
			'g_title_en'	=> 'Bahamas',
		),
		array(
			'g_country_id'	=> '34',
			'g_total_regions'	=> '5',
			'g_total_cities'	=> '123',
			'g_title_ru'	=> 'Бахрейн',
			'g_title_en'	=> 'Bahrain',
		),
		array(
			'g_country_id'	=> '32',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '590',
			'g_title_ru'	=> 'Бангладеш',
			'g_title_en'	=> 'Bangladesh',
		),
		array(
			'g_country_id'	=> '33',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '521',
			'g_title_ru'	=> 'Барбадос',
			'g_title_en'	=> 'Barbados',
		),
		array(
			'g_country_id'	=> '3',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '22826',
			'g_title_ru'	=> 'Беларусь',
			'g_title_en'	=> 'Belarus',
		),
		array(
			'g_country_id'	=> '36',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '11403',
			'g_title_ru'	=> 'Бельгия',
			'g_title_en'	=> 'Belgium',
		),
		array(
			'g_country_id'	=> '35',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '424',
			'g_title_ru'	=> 'Белиз',
			'g_title_en'	=> 'Belize',
		),
		array(
			'g_country_id'	=> '37',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '3459',
			'g_title_ru'	=> 'Бенин',
			'g_title_en'	=> 'Benin',
		),
		array(
			'g_country_id'	=> '38',
			'g_total_regions'	=> '2',
			'g_total_cities'	=> '31',
			'g_title_ru'	=> 'Бермуды',
			'g_title_en'	=> 'Bermuda',
		),
		array(
			'g_country_id'	=> '47',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '218',
			'g_title_ru'	=> 'Бутан',
			'g_title_en'	=> 'Bhutan',
		),
		array(
			'g_country_id'	=> '40',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '11763',
			'g_title_ru'	=> 'Боливия',
			'g_title_en'	=> 'Bolivia',
		),
		array(
			'g_country_id'	=> '235',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '0',
			'g_title_ru'	=> 'Бонайре, Синт-Эстатиус и Саба',
			'g_title_en'	=> 'Bonaire, Sint Eustatius and Saba',
		),
		array(
			'g_country_id'	=> '41',
			'g_total_regions'	=> '3',
			'g_total_cities'	=> '14879',
			'g_title_ru'	=> 'Босния и Герцеговина',
			'g_title_en'	=> 'Bosnia and Herzegovina',
		),
		array(
			'g_country_id'	=> '42',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '460',
			'g_title_ru'	=> 'Ботсвана',
			'g_title_en'	=> 'Botswana',
		),
		array(
			'g_country_id'	=> '43',
			'g_total_regions'	=> '27',
			'g_total_cities'	=> '28573',
			'g_title_ru'	=> 'Бразилия',
			'g_title_en'	=> 'Brazil',
		),
		array(
			'g_country_id'	=> '52',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '23',
			'g_title_ru'	=> 'Виргинские острова, Великобритания',
			'g_title_en'	=> 'British Virgin Islands',
		),
		array(
			'g_country_id'	=> '44',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '221',
			'g_title_ru'	=> 'Бруней',
			'g_title_en'	=> 'Brunei',
		),
		array(
			'g_country_id'	=> '39',
			'g_total_regions'	=> '28',
			'g_total_cities'	=> '6844',
			'g_title_ru'	=> 'Болгария',
			'g_title_en'	=> 'Bulgaria',
		),
		array(
			'g_country_id'	=> '45',
			'g_total_regions'	=> '45',
			'g_total_cities'	=> '7869',
			'g_title_ru'	=> 'Буркина-Фасо',
			'g_title_en'	=> 'Burkina Faso',
		),
		array(
			'g_country_id'	=> '46',
			'g_total_regions'	=> '16',
			'g_total_cities'	=> '1995',
			'g_title_ru'	=> 'Бурунди',
			'g_title_en'	=> 'Burundi',
		),
		array(
			'g_country_id'	=> '103',
			'g_total_regions'	=> '19',
			'g_total_cities'	=> '8137',
			'g_title_ru'	=> 'Кот-д\'Ивуар',
			'g_title_en'	=> 'Côte d\'Ivoire',
		),
		array(
			'g_country_id'	=> '91',
			'g_total_regions'	=> '22',
			'g_total_cities'	=> '7264',
			'g_title_ru'	=> 'Камбоджа',
			'g_title_en'	=> 'Cambodia',
		),
		array(
			'g_country_id'	=> '92',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '7871',
			'g_title_ru'	=> 'Камерун',
			'g_title_en'	=> 'Cameroon',
		),
		array(
			'g_country_id'	=> '10',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '10065',
			'g_title_ru'	=> 'Канада',
			'g_title_en'	=> 'Canada',
		),
		array(
			'g_country_id'	=> '90',
			'g_total_regions'	=> '17',
			'g_total_cities'	=> '256',
			'g_title_ru'	=> 'Кабо-Верде',
			'g_title_en'	=> 'Cape Verde',
		),
		array(
			'g_country_id'	=> '149',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '65',
			'g_title_ru'	=> 'Острова Кайман',
			'g_title_en'	=> 'Cayman Islands',
		),
		array(
			'g_country_id'	=> '213',
			'g_total_regions'	=> '17',
			'g_total_cities'	=> '4503',
			'g_title_ru'	=> 'Центральноафриканская Республика',
			'g_title_en'	=> 'Central African Republic',
		),
		array(
			'g_country_id'	=> '214',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '9005',
			'g_title_ru'	=> 'Чад',
			'g_title_en'	=> 'Chad',
		),
		array(
			'g_country_id'	=> '216',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '3593',
			'g_title_ru'	=> 'Чили',
			'g_title_en'	=> 'Chile',
		),
		array(
			'g_country_id'	=> '97',
			'g_total_regions'	=> '31',
			'g_total_cities'	=> '2861',
			'g_title_ru'	=> 'Китай',
			'g_title_en'	=> 'China',
		),
		array(
			'g_country_id'	=> '98',
			'g_total_regions'	=> '33',
			'g_total_cities'	=> '16768',
			'g_title_ru'	=> 'Колумбия',
			'g_title_en'	=> 'Colombia',
		),
		array(
			'g_country_id'	=> '99',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '430',
			'g_title_ru'	=> 'Коморы',
			'g_title_en'	=> 'Comoros',
		),
		array(
			'g_country_id'	=> '100',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '4963',
			'g_title_ru'	=> 'Конго',
			'g_title_en'	=> 'Congo',
		),
		array(
			'g_country_id'	=> '101',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '17376',
			'g_title_ru'	=> 'Конго, демократическая республика',
			'g_title_en'	=> 'Congo, Democratic Republic',
		),
		array(
			'g_country_id'	=> '150',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '59',
			'g_title_ru'	=> 'Острова Кука',
			'g_title_en'	=> 'Cook Islands',
		),
		array(
			'g_country_id'	=> '102',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '1957',
			'g_title_ru'	=> 'Коста-Рика',
			'g_title_en'	=> 'Costa Rica',
		),
		array(
			'g_country_id'	=> '212',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '9795',
			'g_title_ru'	=> 'Хорватия',
			'g_title_en'	=> 'Croatia',
		),
		array(
			'g_country_id'	=> '104',
			'g_total_regions'	=> '15',
			'g_total_cities'	=> '7129',
			'g_title_ru'	=> 'Куба',
			'g_title_en'	=> 'Cuba',
		),
		array(
			'g_country_id'	=> '138',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '205',
			'g_title_ru'	=> 'Кюрасао',
			'g_title_en'	=> 'Curaçao',
		),
		array(
			'g_country_id'	=> '95',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '638',
			'g_title_ru'	=> 'Кипр',
			'g_title_en'	=> 'Cyprus',
		),
		array(
			'g_country_id'	=> '215',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '15770',
			'g_title_ru'	=> 'Чехия',
			'g_title_en'	=> 'Czech Republic',
		),
		array(
			'g_country_id'	=> '73',
			'g_total_regions'	=> '5',
			'g_total_cities'	=> '7335',
			'g_title_ru'	=> 'Дания',
			'g_title_en'	=> 'Denmark',
		),
		array(
			'g_country_id'	=> '231',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '76',
			'g_title_ru'	=> 'Джибути',
			'g_title_en'	=> 'Djibouti',
		),
		array(
			'g_country_id'	=> '74',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '110',
			'g_title_ru'	=> 'Доминика',
			'g_title_en'	=> 'Dominica',
		),
		array(
			'g_country_id'	=> '75',
			'g_total_regions'	=> '32',
			'g_total_cities'	=> '7371',
			'g_title_ru'	=> 'Доминиканская Республика',
			'g_title_en'	=> 'Dominican Republic',
		),
		array(
			'g_country_id'	=> '54',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '2660',
			'g_title_ru'	=> 'Восточный Тимор',
			'g_title_en'	=> 'East Timor',
		),
		array(
			'g_country_id'	=> '221',
			'g_total_regions'	=> '24',
			'g_total_cities'	=> '6043',
			'g_title_ru'	=> 'Эквадор',
			'g_title_en'	=> 'Ecuador',
		),
		array(
			'g_country_id'	=> '76',
			'g_total_regions'	=> '27',
			'g_total_cities'	=> '8130',
			'g_title_ru'	=> 'Египет',
			'g_title_en'	=> 'Egypt',
		),
		array(
			'g_country_id'	=> '166',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '3117',
			'g_title_ru'	=> 'Сальвадор',
			'g_title_en'	=> 'El Salvador',
		),
		array(
			'g_country_id'	=> '222',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '1355',
			'g_title_ru'	=> 'Экваториальная Гвинея',
			'g_title_en'	=> 'Equatorial Guinea',
		),
		array(
			'g_country_id'	=> '223',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '1000',
			'g_title_ru'	=> 'Эритрея',
			'g_title_en'	=> 'Eritrea',
		),
		array(
			'g_country_id'	=> '14',
			'g_total_regions'	=> '15',
			'g_total_cities'	=> '4854',
			'g_title_ru'	=> 'Эстония',
			'g_title_en'	=> 'Estonia',
		),
		array(
			'g_country_id'	=> '171',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '32',
			'g_title_ru'	=> 'Эсватини',
			'g_title_en'	=> 'Eswatini',
		),
		array(
			'g_country_id'	=> '224',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '8975',
			'g_title_ru'	=> 'Эфиопия',
			'g_title_en'	=> 'Ethiopia',
		),
		array(
			'g_country_id'	=> '208',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '56',
			'g_title_ru'	=> 'Фолклендские острова',
			'g_title_en'	=> 'Falkland Islands',
		),
		array(
			'g_country_id'	=> '204',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '178',
			'g_title_ru'	=> 'Фарерские острова',
			'g_title_en'	=> 'Faroe Islands',
		),
		array(
			'g_country_id'	=> '205',
			'g_total_regions'	=> '5',
			'g_total_cities'	=> '1198',
			'g_title_ru'	=> 'Фиджи',
			'g_title_en'	=> 'Fiji',
		),
		array(
			'g_country_id'	=> '207',
			'g_total_regions'	=> '19',
			'g_total_cities'	=> '15466',
			'g_title_ru'	=> 'Финляндия',
			'g_title_en'	=> 'Finland',
		),
		array(
			'g_country_id'	=> '209',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '72190',
			'g_title_ru'	=> 'Франция',
			'g_title_en'	=> 'France',
		),
		array(
			'g_country_id'	=> '210',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '528',
			'g_title_ru'	=> 'Французская Гвиана',
			'g_title_en'	=> 'French Guiana',
		),
		array(
			'g_country_id'	=> '211',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '293',
			'g_title_ru'	=> 'Французская Полинезия',
			'g_title_en'	=> 'French Polynesia',
		),
		array(
			'g_country_id'	=> '56',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '3526',
			'g_title_ru'	=> 'Габон',
			'g_title_en'	=> 'Gabon',
		),
		array(
			'g_country_id'	=> '59',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '1861',
			'g_title_ru'	=> 'Гамбия',
			'g_title_en'	=> 'Gambia',
		),
		array(
			'g_country_id'	=> '7',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '828',
			'g_title_ru'	=> 'Грузия',
			'g_title_en'	=> 'Georgia',
		),
		array(
			'g_country_id'	=> '65',
			'g_total_regions'	=> '16',
			'g_total_cities'	=> '79543',
			'g_title_ru'	=> 'Германия',
			'g_title_en'	=> 'Germany',
		),
		array(
			'g_country_id'	=> '60',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '8489',
			'g_title_ru'	=> 'Гана',
			'g_title_en'	=> 'Ghana',
		),
		array(
			'g_country_id'	=> '66',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1',
			'g_title_ru'	=> 'Гибралтар',
			'g_title_en'	=> 'Gibraltar',
		),
		array(
			'g_country_id'	=> '71',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '11797',
			'g_title_ru'	=> 'Греция',
			'g_title_en'	=> 'Greece',
		),
		array(
			'g_country_id'	=> '70',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '226',
			'g_title_ru'	=> 'Гренландия',
			'g_title_en'	=> 'Greenland',
		),
		array(
			'g_country_id'	=> '69',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '278',
			'g_title_ru'	=> 'Гренада',
			'g_title_en'	=> 'Grenada',
		),
		array(
			'g_country_id'	=> '61',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '386',
			'g_title_ru'	=> 'Гваделупа',
			'g_title_en'	=> 'Guadeloupe',
		),
		array(
			'g_country_id'	=> '72',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '148',
			'g_title_ru'	=> 'Гуам',
			'g_title_en'	=> 'Guam',
		),
		array(
			'g_country_id'	=> '62',
			'g_total_regions'	=> '22',
			'g_total_cities'	=> '5532',
			'g_title_ru'	=> 'Гватемала',
			'g_title_en'	=> 'Guatemala',
		),
		array(
			'g_country_id'	=> '236',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '49',
			'g_title_ru'	=> 'Гернси',
			'g_title_en'	=> 'Guernsey',
		),
		array(
			'g_country_id'	=> '63',
			'g_total_regions'	=> '34',
			'g_total_cities'	=> '6240',
			'g_title_ru'	=> 'Гвинея',
			'g_title_en'	=> 'Guinea',
		),
		array(
			'g_country_id'	=> '64',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '3699',
			'g_title_ru'	=> 'Гвинея-Бисау',
			'g_title_en'	=> 'Guinea-Bissau',
		),
		array(
			'g_country_id'	=> '58',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '496',
			'g_title_ru'	=> 'Гайана',
			'g_title_en'	=> 'Guyana',
		),
		array(
			'g_country_id'	=> '57',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '8249',
			'g_title_ru'	=> 'Гаити',
			'g_title_en'	=> 'Haiti',
		),
		array(
			'g_country_id'	=> '67',
			'g_total_regions'	=> '19',
			'g_total_cities'	=> '9437',
			'g_title_ru'	=> 'Гондурас',
			'g_title_en'	=> 'Honduras',
		),
		array(
			'g_country_id'	=> '50',
			'g_total_regions'	=> '20',
			'g_total_cities'	=> '15121',
			'g_title_ru'	=> 'Венгрия',
			'g_title_en'	=> 'Hungary',
		),
		array(
			'g_country_id'	=> '86',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '686',
			'g_title_ru'	=> 'Исландия',
			'g_title_en'	=> 'Iceland',
		),
		array(
			'g_country_id'	=> '80',
			'g_total_regions'	=> '36',
			'g_total_cities'	=> '27904',
			'g_title_ru'	=> 'Индия',
			'g_title_en'	=> 'India',
		),
		array(
			'g_country_id'	=> '81',
			'g_total_regions'	=> '34',
			'g_total_cities'	=> '6759',
			'g_title_ru'	=> 'Индонезия',
			'g_title_en'	=> 'Indonesia',
		),
		array(
			'g_country_id'	=> '84',
			'g_total_regions'	=> '31',
			'g_total_cities'	=> '61552',
			'g_title_ru'	=> 'Иран',
			'g_title_en'	=> 'Iran',
		),
		array(
			'g_country_id'	=> '83',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '10404',
			'g_title_ru'	=> 'Ирак',
			'g_title_en'	=> 'Iraq',
		),
		array(
			'g_country_id'	=> '85',
			'g_total_regions'	=> '26',
			'g_total_cities'	=> '8782',
			'g_title_ru'	=> 'Ирландия',
			'g_title_en'	=> 'Ireland',
		),
		array(
			'g_country_id'	=> '147',
			'g_total_regions'	=> '24',
			'g_total_cities'	=> '61',
			'g_title_ru'	=> 'Остров Мэн',
			'g_title_en'	=> 'Isle of Man',
		),
		array(
			'g_country_id'	=> '8',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1263',
			'g_title_ru'	=> 'Израиль',
			'g_title_en'	=> 'Israel',
		),
		array(
			'g_country_id'	=> '88',
			'g_total_regions'	=> '20',
			'g_total_cities'	=> '32458',
			'g_title_ru'	=> 'Италия',
			'g_title_en'	=> 'Italy',
		),
		array(
			'g_country_id'	=> '228',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '2070',
			'g_title_ru'	=> 'Ямайка',
			'g_title_en'	=> 'Jamaica',
		),
		array(
			'g_country_id'	=> '229',
			'g_total_regions'	=> '47',
			'g_total_cities'	=> '1780',
			'g_title_ru'	=> 'Япония',
			'g_title_en'	=> 'Japan',
		),
		array(
			'g_country_id'	=> '237',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '84',
			'g_title_ru'	=> 'Джерси',
			'g_title_en'	=> 'Jersey',
		),
		array(
			'g_country_id'	=> '82',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '676',
			'g_title_ru'	=> 'Иордания',
			'g_title_en'	=> 'Jordan',
		),
		array(
			'g_country_id'	=> '4',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '6370',
			'g_title_ru'	=> 'Казахстан',
			'g_title_en'	=> 'Kazakhstan',
		),
		array(
			'g_country_id'	=> '94',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '4551',
			'g_title_ru'	=> 'Кения',
			'g_title_en'	=> 'Kenya',
		),
		array(
			'g_country_id'	=> '96',
			'g_total_regions'	=> '2',
			'g_total_cities'	=> '116',
			'g_title_ru'	=> 'Кирибати',
			'g_title_en'	=> 'Kiribati',
		),
		array(
			'g_country_id'	=> '105',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '114',
			'g_title_ru'	=> 'Кувейт',
			'g_title_en'	=> 'Kuwait',
		),
		array(
			'g_country_id'	=> '11',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '690',
			'g_title_ru'	=> 'Кыргызстан',
			'g_title_en'	=> 'Kyrgyzstan',
		),
		array(
			'g_country_id'	=> '106',
			'g_total_regions'	=> '18',
			'g_total_cities'	=> '10998',
			'g_title_ru'	=> 'Лаос',
			'g_title_en'	=> 'Laos',
		),
		array(
			'g_country_id'	=> '12',
			'g_total_regions'	=> '110',
			'g_total_cities'	=> '8836',
			'g_title_ru'	=> 'Латвия',
			'g_title_en'	=> 'Latvia',
		),
		array(
			'g_country_id'	=> '109',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '3338',
			'g_title_ru'	=> 'Ливан',
			'g_title_en'	=> 'Lebanon',
		),
		array(
			'g_country_id'	=> '107',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '267',
			'g_title_ru'	=> 'Лесото',
			'g_title_en'	=> 'Lesotho',
		),
		array(
			'g_country_id'	=> '108',
			'g_total_regions'	=> '15',
			'g_total_cities'	=> '5344',
			'g_title_ru'	=> 'Либерия',
			'g_title_en'	=> 'Liberia',
		),
		array(
			'g_country_id'	=> '110',
			'g_total_regions'	=> '22',
			'g_total_cities'	=> '834',
			'g_title_ru'	=> 'Ливия',
			'g_title_en'	=> 'Libya',
		),
		array(
			'g_country_id'	=> '111',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '46',
			'g_title_ru'	=> 'Лихтенштейн',
			'g_title_en'	=> 'Liechtenstein',
		),
		array(
			'g_country_id'	=> '13',
			'g_total_regions'	=> '60',
			'g_total_cities'	=> '22477',
			'g_title_ru'	=> 'Литва',
			'g_title_en'	=> 'Lithuania',
		),
		array(
			'g_country_id'	=> '112',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '705',
			'g_title_ru'	=> 'Люксембург',
			'g_title_en'	=> 'Luxembourg',
		),
		array(
			'g_country_id'	=> '115',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '15309',
			'g_title_ru'	=> 'Мадагаскар',
			'g_title_en'	=> 'Madagascar',
		),
		array(
			'g_country_id'	=> '118',
			'g_total_regions'	=> '27',
			'g_total_cities'	=> '4158',
			'g_title_ru'	=> 'Малави',
			'g_title_en'	=> 'Malawi',
		),
		array(
			'g_country_id'	=> '119',
			'g_total_regions'	=> '16',
			'g_total_cities'	=> '12130',
			'g_title_ru'	=> 'Малайзия',
			'g_title_en'	=> 'Malaysia',
		),
		array(
			'g_country_id'	=> '121',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '82',
			'g_title_ru'	=> 'Мальдивы',
			'g_title_en'	=> 'Maldives',
		),
		array(
			'g_country_id'	=> '120',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '9252',
			'g_title_ru'	=> 'Мали',
			'g_title_en'	=> 'Mali',
		),
		array(
			'g_country_id'	=> '122',
			'g_total_regions'	=> '68',
			'g_total_cities'	=> '347',
			'g_title_ru'	=> 'Мальта',
			'g_title_en'	=> 'Malta',
		),
		array(
			'g_country_id'	=> '125',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '18',
			'g_title_ru'	=> 'Маршалловы Острова',
			'g_title_en'	=> 'Marshall Islands',
		),
		array(
			'g_country_id'	=> '124',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '484',
			'g_title_ru'	=> 'Мартиника',
			'g_title_en'	=> 'Martinique',
		),
		array(
			'g_country_id'	=> '114',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '861',
			'g_title_ru'	=> 'Мавритания',
			'g_title_en'	=> 'Mauritania',
		),
		array(
			'g_country_id'	=> '113',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '527',
			'g_title_ru'	=> 'Маврикий',
			'g_title_en'	=> 'Mauritius',
		),
		array(
			'g_country_id'	=> '126',
			'g_total_regions'	=> '32',
			'g_total_cities'	=> '50784',
			'g_title_ru'	=> 'Мексика',
			'g_title_en'	=> 'Mexico',
		),
		array(
			'g_country_id'	=> '127',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '927',
			'g_title_ru'	=> 'Микронезия, федеративные штаты',
			'g_title_en'	=> 'Micronesia',
		),
		array(
			'g_country_id'	=> '15',
			'g_total_regions'	=> '34',
			'g_total_cities'	=> '1696',
			'g_title_ru'	=> 'Молдова',
			'g_title_en'	=> 'Moldova',
		),
		array(
			'g_country_id'	=> '129',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '6',
			'g_title_ru'	=> 'Монако',
			'g_title_en'	=> 'Monaco',
		),
		array(
			'g_country_id'	=> '130',
			'g_total_regions'	=> '22',
			'g_total_cities'	=> '1461',
			'g_title_ru'	=> 'Монголия',
			'g_title_en'	=> 'Mongolia',
		),
		array(
			'g_country_id'	=> '230',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '3472',
			'g_title_ru'	=> 'Черногория',
			'g_title_en'	=> 'Montenegro',
		),
		array(
			'g_country_id'	=> '131',
			'g_total_regions'	=> '3',
			'g_total_cities'	=> '81',
			'g_title_ru'	=> 'Монтсеррат',
			'g_title_en'	=> 'Montserrat',
		),
		array(
			'g_country_id'	=> '123',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '15883',
			'g_title_ru'	=> 'Марокко',
			'g_title_en'	=> 'Morocco',
		),
		array(
			'g_country_id'	=> '128',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '19945',
			'g_title_ru'	=> 'Мозамбик',
			'g_title_en'	=> 'Mozambique',
		),
		array(
			'g_country_id'	=> '132',
			'g_total_regions'	=> '15',
			'g_total_cities'	=> '25761',
			'g_title_ru'	=> 'Мьянма',
			'g_title_en'	=> 'Myanmar',
		),
		array(
			'g_country_id'	=> '133',
			'g_total_regions'	=> '38',
			'g_total_cities'	=> '1965',
			'g_title_ru'	=> 'Намибия',
			'g_title_en'	=> 'Namibia',
		),
		array(
			'g_country_id'	=> '134',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '23',
			'g_title_ru'	=> 'Науру',
			'g_title_en'	=> 'Nauru',
		),
		array(
			'g_country_id'	=> '135',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '860',
			'g_title_ru'	=> 'Непал',
			'g_title_en'	=> 'Nepal',
		),
		array(
			'g_country_id'	=> '139',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '7490',
			'g_title_ru'	=> 'Нидерланды',
			'g_title_en'	=> 'Netherlands',
		),
		array(
			'g_country_id'	=> '143',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '582',
			'g_title_ru'	=> 'Новая Каледония',
			'g_title_en'	=> 'New Caledonia',
		),
		array(
			'g_country_id'	=> '142',
			'g_total_regions'	=> '17',
			'g_total_cities'	=> '2403',
			'g_title_ru'	=> 'Новая Зеландия',
			'g_title_en'	=> 'New Zealand',
		),
		array(
			'g_country_id'	=> '140',
			'g_total_regions'	=> '17',
			'g_total_cities'	=> '2291',
			'g_title_ru'	=> 'Никарагуа',
			'g_title_en'	=> 'Nicaragua',
		),
		array(
			'g_country_id'	=> '136',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '6839',
			'g_title_ru'	=> 'Нигер',
			'g_title_en'	=> 'Niger',
		),
		array(
			'g_country_id'	=> '137',
			'g_total_regions'	=> '44',
			'g_total_cities'	=> '27274',
			'g_title_ru'	=> 'Нигерия',
			'g_title_en'	=> 'Nigeria',
		),
		array(
			'g_country_id'	=> '141',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '16',
			'g_title_ru'	=> 'Ниуэ',
			'g_title_en'	=> 'Niue',
		),
		array(
			'g_country_id'	=> '148',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '2',
			'g_title_ru'	=> 'Остров Норфолк',
			'g_title_en'	=> 'Norfolk Island',
		),
		array(
			'g_country_id'	=> '173',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '21972',
			'g_title_ru'	=> 'Северная Корея',
			'g_title_en'	=> 'North Korea',
		),
		array(
			'g_country_id'	=> '117',
			'g_total_regions'	=> '84',
			'g_total_cities'	=> '2050',
			'g_title_ru'	=> 'Северная Македония',
			'g_title_en'	=> 'North Macedonia',
		),
		array(
			'g_country_id'	=> '174',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '49',
			'g_title_ru'	=> 'Северные Марианские острова',
			'g_title_en'	=> 'Northern Mariana Islands',
		),
		array(
			'g_country_id'	=> '144',
			'g_total_regions'	=> '20',
			'g_total_cities'	=> '9219',
			'g_title_ru'	=> 'Норвегия',
			'g_title_en'	=> 'Norway',
		),
		array(
			'g_country_id'	=> '146',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '1979',
			'g_title_ru'	=> 'Оман',
			'g_title_en'	=> 'Oman',
		),
		array(
			'g_country_id'	=> '152',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '66110',
			'g_title_ru'	=> 'Пакистан',
			'g_title_en'	=> 'Pakistan',
		),
		array(
			'g_country_id'	=> '153',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '145',
			'g_title_ru'	=> 'Палау',
			'g_title_en'	=> 'Palau',
		),
		array(
			'g_country_id'	=> '154',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '693',
			'g_title_ru'	=> 'Палестинская автономия',
			'g_title_en'	=> 'Palestine',
		),
		array(
			'g_country_id'	=> '155',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '4709',
			'g_title_ru'	=> 'Панама',
			'g_title_en'	=> 'Panama',
		),
		array(
			'g_country_id'	=> '156',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '10804',
			'g_title_ru'	=> 'Папуа — Новая Гвинея',
			'g_title_en'	=> 'Papua New Guinea',
		),
		array(
			'g_country_id'	=> '157',
			'g_total_regions'	=> '18',
			'g_total_cities'	=> '1970',
			'g_title_ru'	=> 'Парагвай',
			'g_title_en'	=> 'Paraguay',
		),
		array(
			'g_country_id'	=> '158',
			'g_total_regions'	=> '25',
			'g_total_cities'	=> '30978',
			'g_title_ru'	=> 'Перу',
			'g_title_en'	=> 'Peru',
		),
		array(
			'g_country_id'	=> '206',
			'g_total_regions'	=> '143',
			'g_total_cities'	=> '32296',
			'g_title_ru'	=> 'Филиппины',
			'g_title_en'	=> 'Philippines',
		),
		array(
			'g_country_id'	=> '159',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1',
			'g_title_ru'	=> 'Питкерн',
			'g_title_en'	=> 'Pitcairn Islands',
		),
		array(
			'g_country_id'	=> '160',
			'g_total_regions'	=> '16',
			'g_total_cities'	=> '40436',
			'g_title_ru'	=> 'Польша',
			'g_title_en'	=> 'Poland',
		),
		array(
			'g_country_id'	=> '161',
			'g_total_regions'	=> '20',
			'g_total_cities'	=> '17972',
			'g_title_ru'	=> 'Португалия',
			'g_title_en'	=> 'Portugal',
		),
		array(
			'g_country_id'	=> '162',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1982',
			'g_title_ru'	=> 'Пуэрто-Рико',
			'g_title_en'	=> 'Puerto Rico',
		),
		array(
			'g_country_id'	=> '93',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '201',
			'g_title_ru'	=> 'Катар',
			'g_title_en'	=> 'Qatar',
		),
		array(
			'g_country_id'	=> '163',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '323',
			'g_title_ru'	=> 'Реюньон',
			'g_title_en'	=> 'Réunion',
		),
		array(
			'g_country_id'	=> '165',
			'g_total_regions'	=> '42',
			'g_total_cities'	=> '13772',
			'g_title_ru'	=> 'Румыния',
			'g_title_en'	=> 'Romania',
		),
		array(
			'g_country_id'	=> '1',
			'g_total_regions'	=> '84',
			'g_total_cities'	=> '158396',
			'g_title_ru'	=> 'Россия',
			'g_title_en'	=> 'Russia',
		),
		array(
			'g_country_id'	=> '164',
			'g_total_regions'	=> '15',
			'g_total_cities'	=> '885',
			'g_title_ru'	=> 'Руанда',
			'g_title_en'	=> 'Rwanda',
		),
		array(
			'g_country_id'	=> '169',
			'g_total_regions'	=> '2',
			'g_total_cities'	=> '205',
			'g_title_ru'	=> 'Сан-Томе и Принсипи',
			'g_title_en'	=> 'São Tomé and Príncipe',
		),
		array(
			'g_country_id'	=> '172',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '82',
			'g_title_ru'	=> 'Святая Елена',
			'g_title_en'	=> 'Saint Helena',
		),
		array(
			'g_country_id'	=> '178',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '133',
			'g_title_ru'	=> 'Сент-Китс и Невис',
			'g_title_en'	=> 'Saint Kitts and Nevis',
		),
		array(
			'g_country_id'	=> '179',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '191',
			'g_title_ru'	=> 'Сент-Люсия',
			'g_title_en'	=> 'Saint Lucia',
		),
		array(
			'g_country_id'	=> '180',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '7',
			'g_title_ru'	=> 'Сент-Пьер и Микелон',
			'g_title_en'	=> 'Saint Pierre and Miquelon',
		),
		array(
			'g_country_id'	=> '177',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '75',
			'g_title_ru'	=> 'Сент-Винсент и Гренадины',
			'g_title_en'	=> 'Saint Vincent and the Grenadines',
		),
		array(
			'g_country_id'	=> '167',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '293',
			'g_title_ru'	=> 'Самоа',
			'g_title_en'	=> 'Samoa',
		),
		array(
			'g_country_id'	=> '168',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '22',
			'g_title_ru'	=> 'Сан-Марино',
			'g_title_en'	=> 'San Marino',
		),
		array(
			'g_country_id'	=> '170',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '2919',
			'g_title_ru'	=> 'Саудовская Аравия',
			'g_title_en'	=> 'Saudi Arabia',
		),
		array(
			'g_country_id'	=> '176',
			'g_total_regions'	=> '11',
			'g_total_cities'	=> '9004',
			'g_title_ru'	=> 'Сенегал',
			'g_title_en'	=> 'Senegal',
		),
		array(
			'g_country_id'	=> '181',
			'g_total_regions'	=> '5',
			'g_total_cities'	=> '6351',
			'g_title_ru'	=> 'Сербия',
			'g_title_en'	=> 'Serbia',
		),
		array(
			'g_country_id'	=> '175',
			'g_total_regions'	=> '26',
			'g_total_cities'	=> '47',
			'g_title_ru'	=> 'Сейшелы',
			'g_title_en'	=> 'Seychelles',
		),
		array(
			'g_country_id'	=> '190',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '5103',
			'g_title_ru'	=> 'Сьерра-Леоне',
			'g_title_en'	=> 'Sierra Leone',
		),
		array(
			'g_country_id'	=> '182',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1',
			'g_title_ru'	=> 'Сингапур',
			'g_title_en'	=> 'Singapore',
		),
		array(
			'g_country_id'	=> '234',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '0',
			'g_title_ru'	=> 'Синт-Мартен',
			'g_title_en'	=> 'Sint Maarten',
		),
		array(
			'g_country_id'	=> '184',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '5112',
			'g_title_ru'	=> 'Словакия',
			'g_title_en'	=> 'Slovakia',
		),
		array(
			'g_country_id'	=> '185',
			'g_total_regions'	=> '206',
			'g_total_cities'	=> '4034',
			'g_title_ru'	=> 'Словения',
			'g_title_en'	=> 'Slovenia',
		),
		array(
			'g_country_id'	=> '186',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '2864',
			'g_title_ru'	=> 'Соломоновы Острова',
			'g_title_en'	=> 'Solomon Islands',
		),
		array(
			'g_country_id'	=> '187',
			'g_total_regions'	=> '18',
			'g_total_cities'	=> '4219',
			'g_title_ru'	=> 'Сомали',
			'g_title_en'	=> 'Somalia',
		),
		array(
			'g_country_id'	=> '227',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '11167',
			'g_title_ru'	=> 'Южно-Африканская Республика',
			'g_title_en'	=> 'South Africa',
		),
		array(
			'g_country_id'	=> '226',
			'g_total_regions'	=> '17',
			'g_total_cities'	=> '16120',
			'g_title_ru'	=> 'Южная Корея',
			'g_title_en'	=> 'South Korea',
		),
		array(
			'g_country_id'	=> '232',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '10',
			'g_title_ru'	=> 'Южный Судан',
			'g_title_en'	=> 'South Sudan',
		),
		array(
			'g_country_id'	=> '87',
			'g_total_regions'	=> '19',
			'g_total_cities'	=> '37925',
			'g_title_ru'	=> 'Испания',
			'g_title_en'	=> 'Spain',
		),
		array(
			'g_country_id'	=> '220',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '14455',
			'g_title_ru'	=> 'Шри-Ланка',
			'g_title_en'	=> 'Sri Lanka',
		),
		array(
			'g_country_id'	=> '188',
			'g_total_regions'	=> '28',
			'g_total_cities'	=> '7600',
			'g_title_ru'	=> 'Судан',
			'g_title_en'	=> 'Sudan',
		),
		array(
			'g_country_id'	=> '189',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '452',
			'g_title_ru'	=> 'Суринам',
			'g_title_en'	=> 'Suriname',
		),
		array(
			'g_country_id'	=> '219',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '9',
			'g_title_ru'	=> 'Шпицберген и Ян Майен',
			'g_title_en'	=> 'Svalbard and Jan Mayen',
		),
		array(
			'g_country_id'	=> '218',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '25450',
			'g_title_ru'	=> 'Швеция',
			'g_title_en'	=> 'Sweden',
		),
		array(
			'g_country_id'	=> '217',
			'g_total_regions'	=> '26',
			'g_total_cities'	=> '9167',
			'g_title_ru'	=> 'Швейцария',
			'g_title_en'	=> 'Switzerland',
		),
		array(
			'g_country_id'	=> '183',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '7881',
			'g_title_ru'	=> 'Сирия',
			'g_title_en'	=> 'Syria',
		),
		array(
			'g_country_id'	=> '192',
			'g_total_regions'	=> '8',
			'g_total_cities'	=> '229',
			'g_title_ru'	=> 'Тайвань',
			'g_title_en'	=> 'Taiwan',
		),
		array(
			'g_country_id'	=> '16',
			'g_total_regions'	=> '3',
			'g_total_cities'	=> '502',
			'g_title_ru'	=> 'Таджикистан',
			'g_title_en'	=> 'Tajikistan',
		),
		array(
			'g_country_id'	=> '193',
			'g_total_regions'	=> '26',
			'g_total_cities'	=> '6565',
			'g_title_ru'	=> 'Танзания',
			'g_title_en'	=> 'Tanzania',
		),
		array(
			'g_country_id'	=> '191',
			'g_total_regions'	=> '76',
			'g_total_cities'	=> '25508',
			'g_title_ru'	=> 'Таиланд',
			'g_title_en'	=> 'Thailand',
		),
		array(
			'g_country_id'	=> '194',
			'g_total_regions'	=> '5',
			'g_total_cities'	=> '3834',
			'g_title_ru'	=> 'Того',
			'g_title_en'	=> 'Togo',
		),
		array(
			'g_country_id'	=> '195',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '2',
			'g_title_ru'	=> 'Токелау',
			'g_title_en'	=> 'Tokelau',
		),
		array(
			'g_country_id'	=> '196',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '105',
			'g_title_ru'	=> 'Тонга',
			'g_title_en'	=> 'Tonga',
		),
		array(
			'g_country_id'	=> '197',
			'g_total_regions'	=> '12',
			'g_total_cities'	=> '472',
			'g_title_ru'	=> 'Тринидад и Тобаго',
			'g_title_en'	=> 'Trinidad and Tobago',
		),
		array(
			'g_country_id'	=> '199',
			'g_total_regions'	=> '25',
			'g_total_cities'	=> '1875',
			'g_title_ru'	=> 'Тунис',
			'g_title_en'	=> 'Tunisia',
		),
		array(
			'g_country_id'	=> '200',
			'g_total_regions'	=> '81',
			'g_total_cities'	=> '14251',
			'g_title_ru'	=> 'Турция',
			'g_title_en'	=> 'Turkey',
		),
		array(
			'g_country_id'	=> '17',
			'g_total_regions'	=> '6',
			'g_total_cities'	=> '105',
			'g_title_ru'	=> 'Туркменистан',
			'g_title_en'	=> 'Turkmenistan',
		),
		array(
			'g_country_id'	=> '151',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '20',
			'g_title_ru'	=> 'Острова Теркс и Кайкос',
			'g_title_en'	=> 'Turks and Caicos Islands',
		),
		array(
			'g_country_id'	=> '198',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '12',
			'g_title_ru'	=> 'Тувалу',
			'g_title_en'	=> 'Tuvalu',
		),
		array(
			'g_country_id'	=> '53',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '505',
			'g_title_ru'	=> 'Виргинские острова, США',
			'g_title_en'	=> 'US Virgin Islands',
		),
		array(
			'g_country_id'	=> '9',
			'g_total_regions'	=> '51',
			'g_total_cities'	=> '169680',
			'g_title_ru'	=> 'США',
			'g_title_en'	=> 'USA',
		),
		array(
			'g_country_id'	=> '201',
			'g_total_regions'	=> '62',
			'g_total_cities'	=> '5031',
			'g_title_ru'	=> 'Уганда',
			'g_title_en'	=> 'Uganda',
		),
		array(
			'g_country_id'	=> '2',
			'g_total_regions'	=> '24',
			'g_total_cities'	=> '15309',
			'g_title_ru'	=> 'Украина',
			'g_title_en'	=> 'Ukraine',
		),
		array(
			'g_country_id'	=> '145',
			'g_total_regions'	=> '7',
			'g_total_cities'	=> '453',
			'g_title_ru'	=> 'Объединенные Арабские Эмираты',
			'g_title_en'	=> 'United Arab Emirates',
		),
		array(
			'g_country_id'	=> '49',
			'g_total_regions'	=> '4',
			'g_total_cities'	=> '18563',
			'g_title_ru'	=> 'Великобритания',
			'g_title_en'	=> 'United Kingdom',
		),
		array(
			'g_country_id'	=> '203',
			'g_total_regions'	=> '19',
			'g_total_cities'	=> '751',
			'g_title_ru'	=> 'Уругвай',
			'g_title_en'	=> 'Uruguay',
		),
		array(
			'g_country_id'	=> '18',
			'g_total_regions'	=> '13',
			'g_total_cities'	=> '2490',
			'g_title_ru'	=> 'Узбекистан',
			'g_title_en'	=> 'Uzbekistan',
		),
		array(
			'g_country_id'	=> '48',
			'g_total_regions'	=> '14',
			'g_total_cities'	=> '1243',
			'g_title_ru'	=> 'Вануату',
			'g_title_en'	=> 'Vanuatu',
		),
		array(
			'g_country_id'	=> '233',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '1',
			'g_title_ru'	=> 'Ватикан',
			'g_title_en'	=> 'Vatican City',
		),
		array(
			'g_country_id'	=> '51',
			'g_total_regions'	=> '25',
			'g_total_cities'	=> '18108',
			'g_title_ru'	=> 'Венесуэла',
			'g_title_en'	=> 'Venezuela',
		),
		array(
			'g_country_id'	=> '55',
			'g_total_regions'	=> '63',
			'g_total_cities'	=> '21018',
			'g_title_ru'	=> 'Вьетнам',
			'g_title_en'	=> 'Vietnam',
		),
		array(
			'g_country_id'	=> '202',
			'g_total_regions'	=> '0',
			'g_total_cities'	=> '32',
			'g_title_ru'	=> 'Уоллис и Футуна',
			'g_title_en'	=> 'Wallis and Futuna',
		),
		array(
			'g_country_id'	=> '78',
			'g_total_regions'	=> '1',
			'g_total_cities'	=> '33',
			'g_title_ru'	=> 'Западная Сахара',
			'g_title_en'	=> 'Western Sahara',
		),
		array(
			'g_country_id'	=> '89',
			'g_total_regions'	=> '21',
			'g_total_cities'	=> '7893',
			'g_title_ru'	=> 'Йемен',
			'g_title_en'	=> 'Yemen',
		),
		array(
			'g_country_id'	=> '77',
			'g_total_regions'	=> '9',
			'g_total_cities'	=> '11152',
			'g_title_ru'	=> 'Замбия',
			'g_title_en'	=> 'Zambia',
		),
		array(
			'g_country_id'	=> '79',
			'g_total_regions'	=> '10',
			'g_total_cities'	=> '1098',
			'g_title_ru'	=> 'Зимбабве',
			'g_title_en'	=> 'Zimbabwe',
		),
	);
